### ISSUE TITLE
Tier 5 construction bot mines incredibly slowly

### ISSUE THREAD

**Issue by MadCat256** [SuperPyroManiac/Rimworld-MiscRobotsPlusPlus#3]
I have a few T5 mining bots in my colony and they all mine at the rate of a low mining skill pawn instead of a high level bot.

**Comment by SuperPyroManiac** [comment]
Yeah I think I found the issue causing it. I will work on a patch for it soon.

**Comment by VeteranXT** [comment]
Constructor, Omni Bots mine at rate of Skill 1

**Comment by MadCat256** [comment]
I think it might have something to do with the bots not being old enough. This is just a guess from looking at the code and what's changed in the base game files. It looks like the initial Misc Robots code may be treating the robots as "humanlike" pawns, and with the 1.4/biotech patch the game started applying and age-based work speed modifier to humanlike pawns. Being essentially age 0, our bots may be getting severely handicapped by it.

**Comment by MadCat256** [comment]
Nope, I was wrong. I dug deeper, did some more testing and found the actual issue. Because Misc. Robots are defined as having a skin type of "mechanoid" the game checks to see if Biotech is installed and if the pawn is a colony mech. If both are true it disables all of the standard worktypes except shooting, and instead looks for "mechEnabledWorkTypes" of which there are none currently defined. in Robots++

A quick and dirty fix is to change the skinType in Misc. Robots' AIRobot_Races.xml from "mechanoid" to "normal" which does unfortunately have the side effect of causing your robots to show wounds like they have flesh instead of metal, but allows them to function normally otherwise.

The long-term fix will be either to define a new robotic but not "mechanoid" skin type for Misc. Robots or to define the proper mechEnabledWorkTypes for the robots in this mod.

**Comment by MadCat256** [comment]
Here's what I found in the code, starting in the "GetDisabledWorkTypes" function

![Rimworld1](https://user-images.githubusercontent.com/103010441/198185140-b396bf32-24bf-4763-89de-8f7a9c0b882b.JPG)
![Rimworld2](https://user-images.githubusercontent.com/103010441/198185152-bfce80df-b70c-43dc-8940-03de761acffb.JPG)
![Rimworld3](https://user-images.githubusercontent.com/103010441/198185157-d3556157-d110-4f5d-ac01-563a7a1ea855.JPG)

**Comment by SuperPyroManiac** [comment]
You are fantastic! I'm going to look into this as well once I get home on
Friday.
